### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by floschne** [ghomasHudson/muld#2]
Hi,

I'm getting a HTTP 429 when I try to download the dataset via HuggingFace as described in your README

**Comment by ghomasHudson** [comment]
> Hi,
> 
> I'm getting a HTTP 429 when I try to download the dataset via HuggingFace as described in your README

Thanks for letting me know - the downloads are a bit flaky because they have to bypass the google drive scan. I'll try and upload a working version at some point this week.

**Comment by floschne** [comment]
push :)

**Comment by ghomasHudson** [comment]
> push :)

It's taking a little longer to fix than I expected - sorry about that. For now I'll upload individual datasets to hf hub directly so you can download them:
```python
ds = datasets.load_dataset("ghomasHudson/muld_NarrativeQA")
ds = datasets.load_dataset("ghomasHudson/muld_HotpotQA")
ds = datasets.load_dataset("ghomasHudson/muld_Character_Archetype_Classification")
ds = datasets.load_dataset("ghomasHudson/muld_OpenSubtitles")
ds = datasets.load_dataset("ghomasHudson/muld_AO3_Style_Change_Detection")
ds = datasets.load_dataset("ghomasHudson/muld_VLSP")
```

Let me know if you have any problems.

**Comment by ghomasHudson** [comment]
> push :)

Have moved the data to HF now, so the normal script should be fixed.
